controllers:
  bot:
    containers:
      app:
        image:
          repository: oreillepale/tds-leaderboard
          tag: "2.0.0"
        envFrom:
          - secretRef:
              name: bot-secret
          
persistence:
  bot-config:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 2Gi
