apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bot-secret
  namespace: tds-leaderboard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: bot-secret
    creationPolicy: Owner
  envFrom:
    - extract:
        key: 9bba40f0-9f9f-4309-b00f-b4b2005f749c
