resources:
  - external-secret.yaml

helmCharts:
  - name: app-template
    version: 5.1.0
    repo: https://bjw-s-labs.github.io/helm-charts
    namespace: tds-leaderboard
    releaseName: tds-leaderboard
    valuesFile: bot-values.yaml
