Namespace: mintbuilder
Name: webapp
Image: risbobo/mintbuilder-web:0.0.1
Replicas: 1
ContainerPort: 80
NodePort: 80
MountPath: /app-data
Path: /mintbuilder-webapp
Storage: 100Mi
Uri: "mintbuilder.supermint.love"