helmCharts:
  - name: homepage
    namespace: homepage
    version: 4.6.0
    repo: ghcr.io/m0nsterrr/helm-charts
    releaseName: homepage
    helm:
      values: | 
        volumeMounts:
          - mountPath: /app/config/bookmarks.yaml
            name: homepage-config
            subPath: bookmarks.yaml
          - mountPath: /app/config/widgets.yaml
            name: homepage-config
            subPath: widgets.yaml
  
