apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  namespace: nativecloudpg
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: cloudflare-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 4623378c-7dd3-48ba-ab84-b418010e05dd
