#resources:
#  - stores
helmCharts:
  - name: external-secrets
    version: 1.2.1
    repo: https://charts.external-secrets.io
    namespace: external-secrets
    releaseName: external-secrets
    valuesFile: values.yaml
