apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
  namespace: bitwarden
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden.svc.cluster.local/object/item/{{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.fields[?@.name==\"{{ .remoteRef.property }}\"].value"