apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-lldap
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: external-secret-lldap
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 01e53ecc-1241-47b3-b1e3-b480004f6818
