apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-s3
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: external-secret-s3
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 305a00a4-97b4-44a2-8ecf-b48000534ecb
