apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: "5.0.0"
    helm:
      values: |
        controllers:
          lldap:
            containers:
              app:
                image:
                  repository: lldap/lldap
                  tag: "2026-05-25-alpine"
                envFrom:
                  - secretRef:
                      name: external-secret-lldap
              litestream:
                image:
                  repository: litestream/litestream
                  tag: "0.5.13"
                args:
                  - replicate
                  - /data/users.db
                  - s3://c8a8be6625a837aef566fbdc4ba32692.r2.cloudflarestorage.com/flickers/litestream
                envFrom:
                  - secretRef:
                      name: external-secret-s3                  
        persistence:
          data:
            enabled: true
            accessMode: ReadWriteOnce
            storageClass: local-path
            size: 5Gi
            advancedMounts:
              lldap:
                app:
                  - path: /data
                litestream:
                  - path: /data

        service:
          app:
            controller: lldap
            ports:
              ui:
                port: 17170
                targetPort: 17170
              lldap:
                port: 3890
                targetPort: 3890
        
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
