controllers:
  pocketid:
    containers:
      app:
        image:
          repository: ghcr.io/pocket-id/pocket-id
          tag: v2.5.0
        env:
          TRUST_PROXY: "true"
          APP_URL: "https://pocketid.flickers.cc" 
        envFrom:
          - secretRef:
              name: pocketid-secret
              
service:
  app:
    controller: pocketid
    ports:
      http:
        port: 1411
        targetPort: 1411
