apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secret
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: authelia-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 59e21716-f656-4043-b292-b40c0135f9b2
    - extract:
        key: 9b2740fb-1df2-45e3-bb81-b40c01170a73
