controllers:
  voidauth:
    containers:
      app:
        image:
          repository: linuxserver/calibre-web
          tag: "0.6.26"
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
              
service:
  app:
    controller: calibre-web
    ports:
      http:
        port: 8083
        targetPort: 8083

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteMany # needed for future litestream sidecar
    storageClass: local-pv
    size: 2Gi

  books:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: nfs-subdir
    size: 10Gi
