apiVersion: postgresql.cnpg.io/v1
kind: SQLJob
metadata:
  name: create-user-and-db
  namespace: authentik
spec:
  cluster: cluster0
  env:
    - name: USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-cred
          key: AUTHENTIK_POSTGRESQL__PASSWORD
  sql: |
    CREATE ROLE authentik WITH LOGIN PASSWORD :'USER_PASSWORD';
    CREATE DATABASE authentik OWNER authentik;

