apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-cred
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: authentik-db-cred
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 14145e56-1b93-4d57-bfac-b3ea01462c77
