resources:
  - database.yaml
  - external-secret.yaml

# helmCharts:
#   - name: authentik
#     repo: https://charts.goauthentik.io
#     version: "2025.10.1"
#     releaseName: authentik
#     namespace: authentik
#     valuesFile: values.yaml
#     includeCRDs: true
