authentik:
  postgresql:
    host: "cluster0-rw.nativecloudpg.svc.cluster.local"
    name: "authentik"
    port: 5432
    user: "authentik"
  
  existingSecret: "authentik-db-cred"

postgresql:
  enabled: false

redis:
  enabled: true
