helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    releaseName: openebs
    namespace: openebs
    version: 4.4.0
    valuesInline:
      engines:
        local:
          enabled: true
        replicated:
          jiva:
            enabled: true
          mayastor:
            enabled: false

resources:
  - sc-local.yaml
  - sc-jiva.yaml
