helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    releaseName: openebs
    namespace: openebs
    version: 4.4.0
    valuesInline:
      engines:
        local:
          enabled: true
        replicated:
          jiva:
            enabled: true
          mayastor:
            enabled: false
      backup:
        enabled: false      # disables MinIO
      monitoring:
        enabled: false      # disables Loki + Prometheus
      loki:
        enabled: false

resources:
  - sc-jiva.yaml
  - sc-hostpath.yaml
  - sc-jiva2.yaml
  - vp.yaml
