apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva3
provisioner: jiva.csi.openebs.io
allowVolumeExpansion: true
parameters:
  replicaCount: "2"
reclaimPolicy: Delete
volumeBindingMode: Immediate
