apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields-wrapped
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli-wrapped.external-secrets.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}"
      result:
        jsonPath: $