controllers:
  bitwarden:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/larivierec/bitwarden-cli
          tag: 2024.9.0
        envFrom:
          - secretRef:
              name: bitwarden-cli
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "curl -X POST -s http://127.0.0.1:8087/sync | jq -e '.success == true'",
                  ]
              initialDelaySeconds: 20
              failureThreshold: 5
              timeoutSeconds: 3
              periodSeconds: 240
          readiness:
            enabled: false

service:
  app:
    controller: bitwarden
    ports:
      http:
        port: 8087
