apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: grimmory
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 4ad71fd8-1a61-4c03-b3df-b433005695b6
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
