resources:
  - external-secret.yaml
  - webdav-config.yaml

helmCharts:
  - name: app-template
    version: 5.1.0
    repo: https://bjw-s-labs.github.io/helm-charts
    namespace: grimmory
    releaseName: grimmory
    valuesFile: values.yaml
