controllers:
  grimmory:
    containers:
      app:
        image:
          repository: grimmory/grimmory
          tag: "v2.2.1"
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
          DATABASE_URL: jdbc:mariadb://mariadb.grimmory.svc.cluster.local:3306/grimmory
          DATABASE_USERNAME: grimmory
          DATABASE_PASSWORD: 
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          volumeMounts:
            - name: grimmory-data
              mountPath: /config
            - name: grimmory-books
              mountPath: /books
            - name: grimmory-bookdrop
              mountPath: /bookdrop
  mariadb:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/mariadb
          tag: "11.4.5"
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
          MYSQL_DATABASE: grimmory
          MYSQL_USER: grimmory
          MYSQL_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          MYSQL_ROOT_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: ROOT_PASSWORD                  
        volumeMounts:
          - name: mariadb-config
            mountPath: /config
            
service:
  app:
    controller: grimmory
    ports:
      http:
        port: 6060
        targetPort: 6060
  mariadb:
    controller: mariadb
    ports:
      db:
        port: 3306
        targetPort: 3306

persistence:
  mariadb-config:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 5Gi

  grimmory-data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce # needed for future litestream sidecar
    storageClass: local-path
    size: 5Gi

  grimmory-books:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: nfs-subdir
    size: 10Gi

  grimmory-bookdrop:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: nfs-subdir
    size: 2Gi
