controllers:
  grimmory:
    containers:
      app:
        image:
          repository: grimmory/grimmory
          tag: "latest"
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
          DATABASE_URL: jdbc:mariadb://grimmory-mariadb.grimmory.svc.cluster.local:3306/grimmory
          DATABASE_USERNAME: grimmory
          DATABASE_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
  mariadb:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/mariadb
          tag: "11.4.10"
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
          MYSQL_DATABASE: grimmory
          MYSQL_USER: grimmory
          MYSQL_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          MYSQL_ROOT_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: ROOT_PASSWORD
  webdav:
    containers:
      app:
        image:
          repository: ghcr.io/hacdias/webdav
          tag: "v5.11.8"
        env:
          ENV_USERNAME:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: WEBDAV_USERNAME
          ENV_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: WEBDAV_PASSWORD

service:
  app:
    controller: grimmory
    ports:
      http:
        port: 6060
        targetPort: 6060
  mariadb:
    controller: mariadb
    ports:
      db:
        port: 3306
        targetPort: 3306
  webdav:
    controller: webdav
    ports:
      http:
        port: 6065
        targetPort: 6065

persistence:
  mariadb-config:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 5Gi
    advancedMounts:
      mariadb:
        app:
          - path: /config
  grimmory-data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 5Gi
    advancedMounts:
      grimmory:
        app:
          - path: /config
  grimmory-books:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: nfs-subdir
    size: 10Gi
    advancedMounts:
      grimmory:
        app:
          - path: /books
      webdav:
        app:
          - path: /data
  grimmory-bookdrop:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: nfs-subdir
    size: 2Gi
    advancedMounts:
      grimmory:
        app:
          - path: /bookdrop
  webdav-config:
    enabled: true
    type: configMap
    name: webdav-config
    advancedMounts:
      webdav:
        app:
          - path: /config.yml
            subPath: config.yaml
