apiVersion: v1
kind: ConfigMap
metadata:
  name: webdav-config
  namespace: grimmory
data:
  config.yaml: |
    address: 0.0.0.0
    port: 6065
    directory: /data
    permissions: CRUD
    users:
      - username: "{env}ENV_USERNAME"
        password: "{env}ENV_PASSWORD"
