apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cred
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: postgres-cred
    creationPolicy: Owner
  data:
    - secretKey: password           # for CNPG bootstrap
      remoteRef:
        key: e614b470-c7cb-4e87-8093-b46e006fb385
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_PASSWORD  # for Immich values.yaml
      remoteRef:
        key: e614b470-c7cb-4e87-8093-b46e006fb385
        property: POSTGRES_PASSWORD
