apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cred
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: postgres-cred
    creationPolicy: Owner
    template:
      data:
        username: immich                          # for CNPG bootstrap
        password: "{{ .POSTGRES_PASSWORD }}"     # for CNPG bootstrap
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"  # for Immich values.yaml
  dataFrom:
    - extract:
        key: e614b470-c7cb-4e87-8093-b46e006fb385
