apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-path
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:14.18-0.4.3 #ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: postgres-cred
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  postgresql:
    shared_preload_libraries:
      - "vchord.so"

