immich:
  persistence:
    library:
      existingClaim: immich-library

env:
  DB_HOSTNAME: "immich-database-rw"
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: postgres-cred
        key: POSTGRES_PASSWORD
  REDIS_HOSTNAME: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"

valkey:
  enabled: false

server:
  ingress:
    main:
      enabled: false
