apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bwsecret
  namespace: twingate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: bwsecret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 547c7176-99c6-4aec-b9a3-b3da011c79f8
