connector:
  enabled: true  
  network: "<network_slug>"
  accessToken: "<token>"
  refreshToken: "<token>"

replicaCount: 2

image:
  repository: twingate/connector
  tag: "1.84.0"
  pullPolicy: IfNotPresent

envFrom:
  - secretRef:
      name: twingate-connector
