apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: single-image
    repo: https://github.com/OreillePale/herminius/charts
    version: 0.1.0
    valuesFile: values.yaml
    releaseName: 1.0.0