Namespace: otterwiki
Name: otterwiki
Image: redimp/otterwiki:2
Replicas: 1
ContainerPort: 80
NodePort: 80
MountPath: /app-data
Path: /otterwiki
Storage: 5Gi 
Uri: "otterwiki.herminius.xyz"
StorageClass: nfs-csi-v3