{{- if and .Values.esoSecret.secretName .Values.esoSecret.storeName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.esoSecret.secretName }}
  namespace: {{ .Values.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.esoSecret.storeName }}
    kind: SecretStore
  target:
    name: {{ .Values.esoSecret.secretName }}
    creationPolicy: Owner
  dataFrom:
    - key: {{ .Values.esoSecret.secretKey }}
{{- end }}