{{- if and .Values.esoSecret.enabled .Values.esoSecret.secretName .Values.esoSecret.storeName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.esoSecret.secretName }}
  namespace: {{ .Values.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.esoSecret.storeName }}
    kind: {{ default "SecretStore" .Values.esoSecret.kind }}
  target:
    name: {{ .Values.esoSecret.secretName }}
    creationPolicy: Owner
  {{- if .Values.esoSecret.extractKey }}
  dataFrom:
    - extract:
        key: {{ .Values.esoSecret.extractKey }}
  {{- else if .Values.esoSecret.data }}
  data:
  {{- toYaml .Values.esoSecret.data | nindent 4 }}
  {{- end }}
{{- end }}