{{- if .Values.BwSecret -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.Name }}-bwsecret
  namespace: {{ .Values.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: {{ .Values.Name }}-bwsecret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.BwSecret }}
{{- end -}}