{{- if .Values.Storage -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.Name }}-nfs-claim
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: {{ .Values.Storage }}
{{- end -}}