{{- if .Values.Storage -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.Name }}-nfs-claim
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.StorageClass | default "nfs-csi-v6" }}
  resources:
    requests:
      storage: {{ .Values.Storage }}
{{- end -}}