apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.2.2  # check latest version in the repo
    helm:
      values: |
        nfs:
          server: 10.43.0.4
          path: /
        storageClass:
          create: true
          name: nfs-csi-v3
          defaultClass: true
          reclaimPolicy: Retain
          volumeBindingMode: Immediate
          allowVolumeExpansion: true
          pathPattern: "${.PVC.namespace}/${.PVC.name}"
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
