apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

#resources:
#  - https://github.com/zalando/postgres-operator/manifests/postgres-operator-crds.yaml

helmCharts:
  # Postgres Operator
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
    version: 1.15.1   
    releaseName: postgres-operator
    valuesInline:
      replicaCount: 1
      namespace: postgres-operator

  # Postgres Operator UI
  - name: postgres-operator-ui
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui/
    version: 1.15.1   
    releaseName: postgres-operator-ui
    valuesInline:
      replicaCount: 1
      namespace: postgres-operator
