apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metrics-secret
  namespace: metrics
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: metrics-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 9c794397-6d95-43d3-978b-b4cd00f9e9c9
