helmCharts:
  # - name: influxdb3-core
  #   repo: https://helm.influxdata.com/
  #   version: "0.1.1"
  #   releaseName: influxdb3-core
  #   namespace: metrics
  #   valuesFile: influxdb3-values.yaml

  - name: telegraf
    repo: https://helm.influxdata.com/
    version: "1.8.76"
    releaseName: telegraf
    namespace: metrics
    valuesFile: telegraf-values.yaml

  helmCharts:
  - name: influxdb2
    repo: https://helm.influxdata.com/
    version: "2.1.2"
    releaseName: influxdb2
    namespace: influxdb
    valuesFile: influxdb3-values.yaml
