resources:
  - external-secret.yaml

helmCharts:
  - name: telegraf-ds
    repo: https://helm.influxdata.com/
    version: "1.1.56"
    releaseName: telegraf-ds
    namespace: metrics
    valuesFile: telegraf-values.yaml

  - name: influxdb2
    repo: https://helm.influxdata.com/
    version: "2.1.2"
    releaseName: influxdb2
    namespace: metrics
    valuesFile: influxdb3-values.yaml

  - name: grafana
    repo: https://grafana-community.github.io/helm-charts
    version: "13.2.5"
    releaseName: grafana
    namespace: metrics
    valuesFile: grafana-values.yaml
    
