apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-cli
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: HEAD
    path: apps/bw-cli
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true