apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-cred
  namespace: pangolin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: newt-cred
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 93e58edb-6b9c-436d-b738-b3df0067886f
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
