apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hub-secret
  namespace: beszel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: hub-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: e1f97758-8140-4ab8-acdd-b49800aeb5ec
