apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hub-secret
  namespace: beszel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: hub-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 04d5f0f7-8772-4845-a16b-b498010ce7d4
