resources:
  - external-secret.yaml
  - agents.yaml

helmCharts:
  - name: app-template
    version: 5.1.0
    repo: https://bjw-s-labs.github.io/helm-charts
    namespace: beszel
    releaseName: beszel-server
    valuesFile: server-values.yaml
