resources:
  - voidauth-secret.yaml

helmCharts:
  - name: app-template
    version: 5.0.1
    repo: https://bjw-s-labs.github.io/helm-charts
    namespace: voidauth
    releaseName: voidauth
    valuesFile: values.yaml
