apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voidauth-secret
  namespace: voidauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: voidauth-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 8cad8869-6de8-44aa-a01e-b40d015741d6
