Namespace: adventea
Name: adventea
Image: oreillepale/adventea:latest
Replicas: 1
Storage: 10Mi
esoSecret:
  enabled: true
  secretName: adventea-secrets
  storeName: bitwarden-fields
  kind: ClusterSecretStore
  extractKey: c15b75f1-6732-4c94-926e-05f8d4fd0076