Namespace: adventea
Name: adventea
Image: oreillepale/adventea:latest
Replicas: 1
Storage: 10Mi
esoSecret:
  secretName: adventea
  storeName: bitwarden-fields
  secretKey: 693f3ce4-0a1a-421a-b5bc-5a3d27fe6806