apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-secrets-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitwarden.com
    chart: bitwarden-secrets-operator
    targetRevision: 1.1.0
    helm:
      releaseName: sm-operator
      values: |
        installCRDs: true

        operator:
          logLevel: info

  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden-sm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
