# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://charts.external-secrets.io
#     chart: external-secrets
#     targetRevision: 0.20.1
#     helm:
#       releaseName: external-secrets
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: external-secrets
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/external-secrets/external-secrets
    targetRevision: v0.20.1
    path: deploy/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.20.1
    helm:
      releaseName: external-secrets
      parameters:
        - name: installCRDs
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

