apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otterwiki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: HEAD
    path: charts/singleimage
    helm:
      values: |
        Namespace: grafana
        Name: grafana
        Image: grafana/grafana-oss
        Replicas: 1
        ContainerPort: 3000
        NodePort: 33000
        MountPath: /var/lib/grafana
        Path: /grafana
        Storage: 5Gi
        Uri: "grafana.herminius.xyz"
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true