apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  type: NodePort
  selector:
    app: longhorn-frontend
  ports:
    - protocol: TCP
      port: 9500       # ClusterIP port
      targetPort: 9500 # Pod port
      nodePort: 30500  # NodePort you want to use
