apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          service:
            ui:
              type: NodePort
              nodePort: 30500
          ingress:
            enabled: true
            # This will create a Traefik ingress
            hosts:
              - host: longhorn.local
                paths:
                  - path: /
                    pathType: Prefix
            tls: []
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
