apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minbuilder-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: HEAD
    path: charts/singleimage
    helm:
      valueFiles:
        - ../../apps/mintbuilder-bot/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mintbuilder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minbuilder-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: HEAD
    path: charts/singleimage
    helm:
      valueFiles:
        - ../../apps/mintbuilder-db/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mintbuilder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minbuilder-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: HEAD
    path: charts/singleimage
    helm:
      valueFiles:
        - ../../apps/mintbuilder-webapp/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mintbuilder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true