apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: main
    path: apps/nfs-csi
    kustomize:
      buildOptions: --enable-helm

  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-csi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
