apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    chart: csi-driver-nfs
    targetRevision: 4.13.1
    helm:
      values: |
        controller:
          runOnControlPlane: true
        storageClass:
          create: true
          name: nfs-subdir
          defaultClass: true
          allowVolumeExpansion: true
          reclaimPolicy: Retain
          parameters:
            server: 192.168.1.8
            share: /mnt/nas/data
            subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}"
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas0-nfs
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  server: 192.168.1.70
  share: /mnt/HDD-pool/NFS0/cluster
  subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}"
mountOptions:
  - nfsvers=4
