apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-csi/csi-driver-nfs
    path: deploy/kubernetes-helm
    targetRevision: master
    helm:
      values: |
        nfs:
          server: 192.168.1.8   # Pi NAS static IP
          path: /mnt/nas         # Root folder on the NFS server
        storageClass:
          name: nfs-subdir
          defaultClass: true
          allowVolumeExpansion: true
        pv:
          reclaimPolicy: Retain     # Keep data if PVC is deleted
        pvc:
          subdirectoryPattern: "{{ .PVC.Namespace }}-{{ .PVC.Name }}"  # Human-readable subfolders
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
