apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: main
    path: apps/twingate
  destination:
    server: https://kubernetes.default.svc
    namespace: twingate
  helm:
    valueFile:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
