apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OreillePale/herminius
    targetRevision: HEAD
    path: otterwiki-test
  destination:
    server: https://kubernetes.default.svc
    namespace: wiki2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true