controllers:
  redis:
    containers:
      app:
        image:
          repository: bitnami/redis
          tag: "sha256-fe9accf438c086794b3708aca6796b94115836aca9f373d53942058380dcac11"
        env:
          ALLOW_EMPTY_PASSWORD: "yes"

service:
  app:
    controller: redis
    ports:
      http:
        port: 6379
        targetPort: 6379
