controllers:
  redis:
    containers:
      app:
        image:
          repository: redis
          tag: "8.10.0-alpine"

service:
  app:
    controller: redis
    ports:
      http:
        port: 6379
        targetPort: 6379
