apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-backup-pvc
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas0-nfs
  resources:
    requests:
      storage: 2Gi
