apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: "3.2.0"
    helm:
      values: |
        replicaCount: 0
        podSecurityContext:
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
    
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
    
        persistence:
          config:
            enabled: true
            size: 10Gi
            storageClass: local-path
            accessModes:
              - ReadWriteMany
    
          media:
            enabled: true
            existingClaim: media2

          backups:
            enabled: true
            size: 2Gi
            storageClass: nfs-subdir
            mountPath: /config/data/backups
            accessMode: ReadWriteOnce

  destination:
    server: https://kubernetes.default.svc
    namespace: arrstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
