controllers:
  profilarr:
    containers:
      app:
        image:
          repository: ghcr.io/dictionarry-hub/profilarr
          tag: "2.0.9"
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
          ORIGIN: https://profilarr.flickers.cc
          
persistence:
  profilarr-config:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 5Gi
    advancedMounts:
      profilarr:
        app:
          - path: /config

service:
  app:
    controller: profilarr
    ports:
      http:
        port: 6868
        targetPort: 6868

