apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1.3Ti
  accessModes:
    - ReadWriteMany   # allows multiple pods to write at once
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nas/media
    server: 192.168.1.8
