apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media2
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: truenas-root-nobackup
