apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-home-lab.github.io/helm-charts/
    chart: qbittorrent
    targetRevision: "14.2.1"
    helm:
      values: |
        podSecurityContext:
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        persistence:
          config:
            enabled: true
            size: 2Gi
            storageClass: nfs-subdir
          media:
            enabled: true
            existingClaim: media
  destination:
    server: https://kubernetes.default.svc
    namespace: arrstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
