apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-home-lab.github.io/helm-charts/
    chart: radarr
    targetRevision: "17.4.0"
    helm:
      values: |
        podSecurityContext:
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
        persistence:
          config:
            enabled: true
            size: 2Gi
            storageClass: nfs-subdir
          media:
            enabled: true
            existingClaim: media
  destination:
    server: https://kubernetes.default.svc
    namespace: arrstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
