apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-root-nobackup
  resources:
    requests:
      storage: 2Gi
