apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-secret
  namespace: arrstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: seerr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: 81112238-43f3-4838-b923-b40f01173293
