apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-secret
  namespace: arrstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields-wrapped
    kind: ClusterSecretStore
  target:
    name: slskd-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ce429756-bd11-4bca-9fbd-b4d6011c2535
