controllers:
  slskd:
    containers:
      app:
        image:
          repository: slskd/slskd
          tag: "0.26.0"
        env:
          SLSKD_REMOTE_CONFIGURATION: "true"
          SLSKD_DOWNLOADS_DIR: /downloads
        envFrom:
          - secretRef:
              name: slskd-secret

persistence:
  config:
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 500Mi
    advancedMounts:
      slskd:
        app:
          - path: /app

  media:
    type: persistentVolumeClaim
    existingClaim: media2
    advancedMounts:
      slskd:
        app:
          - path: /downloads
            subPath: download/slskd

service:
  app:
    controller: slskd
    ports:
      http:
        port: 5030
      https:
        port: 5031
      incoming:
        port: 50300
