apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-home-lab.github.io/helm-charts/
    chart: sonarr
    targetRevision: "17.2.1"
    helm:
      values: |
        podSecurityContext:
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
        persistence:
          config:
            enabled: true
            size: 2Gi
            storageClass: longhorn-double
            # Mount the SMB media PVC like other volumes
          media:
            enabled: true
            existingClaim: smb-media-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: arrstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
