controllers:
  soularr:
    initContainers:
      config:
        image:
          repository: python
          tag: 3.13-alpine

        env:
          - name: LIDARR_API_KEY
            valueFrom:
              secretKeyRef:
                name: slskd-secret
                key: LIDARR_API_KEY

          - name: SLSKD_API_KEY
            valueFrom:
              secretKeyRef:
                name: slskd-secret
                key: SLSKD_API_KEY

        command:
          - /bin/sh
          - -c
          - |
            set -e

            if [ ! -f /data/config.ini ]; then
              echo "/data/config.ini not found, downloading default config"
              python -c "import urllib.request as u; u.urlretrieve('https://raw.githubusercontent.com/mrusse/soularr/main/config.ini', '/data/config.ini.tmp')"
              mv /data/config.ini.tmp /data/config.ini
            fi

            echo "installing crudini"
            pip install --no-cache-dir --root-user-action=ignore crudini

            echo "updating .ini keys"
            crudini --set --existing /data/config.ini Lidarr api_key "$LIDARR_API_KEY"
            crudini --set --existing /data/config.ini Slskd api_key "$SLSKD_API_KEY"

            ls -l /data

    containers:
      app:
        image:
          repository: mrusse08/soularr
          tag: v1.2.2
        env:
          SCRIPT_INTERVAL: 300
          TZ: "ETC/UTC"
        envFrom:
          - secretRef:
              name: slskd-secret

persistence:
  data:
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 500Mi
    advancedMounts:
      soularr:
        config:
          - path: /data
        app:
          - path: /data

  media:
    type: persistentVolumeClaim
    existingClaim: media2
    advancedMounts:
      soularr:
        app:
          - path: /downloads
            subPath: download/slskd

# service:
#   app:
#     controller: soularr
#     ports:
#       http:
#         port: 5030
#       https:
#         port: 5031
#       incoming:
#         port: 50300
