apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: download-tools
          image: alpine:3.18
          command: ["sh", "-c"]
          args:
            - |
              if [ ! -f /custom-tools/argocd-vault-plugin ]; then
                wget -O /custom-tools/argocd-vault-plugin \
                https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.16.1/argocd-vault-plugin_1.16.1_linux_amd64 && \
                chmod +x /custom-tools/argocd-vault-plugin
              fi
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools

      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/argocd-vault-plugin
              subPath: argocd-vault-plugin
              readOnly: true

      volumes:
        - name: custom-tools
          persistentVolumeClaim:
            claimName: argocd-custom-tools
